### ISSUE TITLE
run_install with --global throws permission denied

### ISSUE THREAD

**Issue by rhyek** [pnpm/action-setup#10]
With config:
```yaml
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.17.2
        run_install: |
          - args: [--global, typescript, ts-node]
```

I get the following:
 ```sh
Run pnpm/action-setup@v1.2.1
  with:
    version: 5.17.2
    run_install: - args: [--global, typescript, ts-node]
  
    dest: ~/setup-pnpm
    bin_dest: ~/setup-pnpm/.bin
    registry: https://registry.npmjs.com
  env:
    DOCKER_BUILDKIT: 1
Running self-installer...
  Downloading https://registry.npmjs.org/pnpm/-/pnpm-5.17.2.tgz
Installation Completed!
Running pnpm install --global typescript ts-node...
   ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
  
  
Error: Command pnpm install --global typescript ts-node (cwd: undefined) exits with status 1
```

**Comment by KSXGitHub** [comment]
I must know the cause before I fix this. Can you please try this?

```yaml
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.17.2
        run_install: false

  - run: pnpm i -g typescript ts-node
```

---

BTW, why didn't you just add `typescript` and `ts-node` to `devDependencies` in `package.json` and then use `pnpx` to execute `tsc` and `ts-node`?
