### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/home/runner/setup-pnpm/bin/pnpm.js'

### ISSUE THREAD

**Issue by humphd** [pnpm/action-setup#13]
In my workflow I have:

```yml
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 6.0.1
          run_install: true
```

Which causes the following error:

```bash
Run pnpm/action-setup@v1.2.1
  with:
    version: 6.0.1
    run_install: true
    dest: ~/setup-pnpm
    bin_dest: ~/setup-pnpm/.bin
    registry: https://registry.npmjs.com
Running self-installer...
  Downloading https://registry.npmjs.org/pnpm/-/pnpm-6.0.1.tgz
  [Error: ENOENT: no such file or directory, stat '/home/runner/setup-pnpm/bin/pnpm.js'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/home/runner/setup-pnpm/bin/pnpm.js'
  }
```
