### ISSUE TITLE
keep getting error in random places (pnpm, node, install) in self-hosted

### ISSUE THREAD

**Issue by althafdemiandra** [pnpm/action-setup#149]
Im using self-hosted github action with multiple runners (5 runners)

`Linux · x64 · Self-hosted`

i keep getting error in random places, sometimes its on `pnpm/actions-setup`, it also happened in  `actions/setup-node`,
the other it would happend in `pnpm install`.  

I need to retry it manually once or twice to make it work. I think the cleanup is not really cleaned things up, any idea why? thanks

## Error Example
```
Run pnpm/action-setup@v4
  with:
    version: 8
    run_install: false
    dest: ~/setup-pnpm
    package_json_file: package.json
    standalone: false
Running self-installer...
  Error: Error: ENOTEMPTY: directory not empty, rmdir '/home/runner/setup-pnpm'
    code: 'ENOTEMPTY',
    syscall: 'rmdir',
    path: '/home/runner/setup-pnpm'
  }
```

```
Run actions/setup-node@v4
  with:
    node-version: 20.9.*
    cache: pnpm
    always-auth: false
    check-latest: false
    token: ***
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Found in cache @ /home/runner/runner-3/_work/_tool/node/20.9.0/x64
Environment details
  node: v20.9.0
  npm: 10.1.0
  yarn: 
Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

## Workflow example
```
name: Typechecking

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
    types: [opened, synchronize, reopened, ready_for_review] # Don't run if draft

# Cancel current running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Typecheck
    if: github.event.pull_request.draft == false
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.*
          cache: 'pnpm'
      - name: install deps
        run: pnpm install
      - name: run typechecker
        run: pnpm run ts-lint

```
