### ISSUE TITLE
Partial cache re-use on pnpm install --frozen-lockfile

### ISSUE THREAD

**Issue by samuelfullerthomas** [pnpm/action-setup#153]
👋  I have an issue using this action with the following github action setup 

```yaml
runs:
    using: composite
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@4 # v4
        - name: Install Node & NPM
          uses: actions/setup-node@4 # v4
          with:
              node-version-file: '.nvmrc'
              cache: 'pnpm'
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
```

The issue is the cache is restored but it isn't fully re-used.

When the installation happening, I see only about half of the packages. are reused:

Progress: resolved 2359, reused 1037, downloaded 141, added 1171

Locally, all the packages are reusued.

What could be causing this? how can I debug it?
