### ISSUE TITLE
ERR_PNPM_GIT_UNCLEAN  Unclean working tree. Commit or stash changes first.

### ISSUE THREAD

**Issue by seepine** [pnpm/action-setup#163]
SOS! Why are there file changes?

package.json
```json
{
  "dependencies": {
    "https-proxy-agent": "~7.0.1",
    "js-sha256": "~0.11.0",
    "ws": "~8.13.0"
  },
  "devDependencies": {
    "@types/ws": "~8.5.5",
    "@types/yargs": "~17.0.24",
    "glob": "~11.0.2",
    "terser": "~5.39.2",
    "typescript": "~5.2.2"
  },
  "packageManager": "pnpm@10.11.0"
}
```

publish.yml
```yml
name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Build
        run: pnpm i --frozen-lockfile && pnpm build

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
          npm whoami          

      - name: Publish to npm
        run: pnpm publish
```

![Image](https://github.com/user-attachments/assets/aff2b6d7-7334-47d8-a0a1-c4ee3cfbf880)
