### ISSUE TITLE
feature request: built-in pnpm modules cache manager

### ISSUE THREAD

**Issue by septs** [pnpm/action-setup#19]
Built-in pnpm modules cache manager

Reduce boilerplate statements

e.g:
```yaml
- uses: pnpm/action-setup@v2.0.1
  with:
    version: latest
    cache: true
```
