### ISSUE TITLE
Pipelines fail with `SyntaxError: Unexpected token`

### ISSUE THREAD

**Issue by gaggle** [pnpm/action-setup#22]
Hi, we see occasional failed pipelines because, well, **something** goes wrong in `pnpm/action-setup`:

```
Running self-installer...
  [stdin]:1
  <HTML>
  ^
  SyntaxError: Unexpected token '<'
      at new Script (vm.js:84:7)
      at createScript (vm.js:258:10)
      at Object.runInThisContext (vm.js:306:10)
      at Object.<anonymous> ([stdin]-wrapper:9:26)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at evalScript (internal/process/execution.js:80:25)
      at internal/main/eval_stdin.js:29:5
      at Socket.<anonymous> (internal/process/execution.js:192:5)
      at Socket.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
Error: Something does wrong, self-installer exits with code 1
Installation Completed!
Running pnpm recursive install --frozen-lockfile
Error: Command pnpm recursive install --frozen-lockfile (cwd: undefined) exits with status 127
```

I'm not sure if it's [this line](https://github.com/pnpm/action-setup/blob/master/src/install-pnpm/run.ts#L22) `const response = await fetch('https://pnpm.js.org/pnpm.js')` that might fail? If it somehow gets an HTML response? So if pnpm.js.org fails to return the `pnpm.js` script for a splitsecond, instead returning an HTML error page, then that could happen?

Will maintainers consider a retry mechanism to increase resilience? If the request is the cause of this error then an exponential backoff could work well, to try a couple times before giving up. WDYT?

**Comment by gaggle** [comment]
Mm.. just got another error. Maybe it's not random request/response errors if they occur so close together… could the endpoint be rate-limited? If response headers indicate when another request is allowed this action could delay until that time?

I assume the file itself cannot be locally cached, but I'm not really sure what's possible in the GitHub Actions infrastructure.

**Comment by bkniffler** [comment]
Just got the same issue with
```
- uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
```

<img width="805" alt="Bildschirmfoto 2021-12-15 um 13 28 48" src="https://user-images.githubusercontent.com/4349324/146186814-743b452e-f09a-4858-8479-9193205d4767.png">

**Comment by hikariNTU** [comment]
Same issue in Github matrix actions:

```
Run pnpm/action-setup@v2.1.0
  with:
    version: latest
    dest: ~/setup-pnpm
    run_install: null
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Running self-installer...
  [stdin]:1
  <HTML>
  ^
  
  SyntaxError: Unexpected token '<'
      at new Script (vm.js:84:7)
      at createScript (vm.js:258:10)
      at Object.runInThisContext (vm.js:306:10)
      at Object.<anonymous> ([stdin]-wrapper:9:26)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at evalScript (internal/process/execution.js:80:25)
      at internal/main/eval_stdin.js:29:5
      at Socket.<anonymous> (internal/process/execution.js:192:5)
      at Socket.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
Error: Something went wrong, self-installer exits with code 1
Installation Completed!
```

We also set npmrc before installing pnpm:

```
Run actions/setup-node@v2
  with:
    node-version: 16.x
    registry-url: https://npm.pkg.github.com
    scope: ***
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ /opt/hostedtoolcache/node/16.13.2/x64
```

But these setting should not be a problem.

And these actions only fail in an action
![image](https://user-images.githubusercontent.com/18393696/154068035-bdc435ea-62bd-4c55-8245-136d2ff57f72.png)

We will try to combine these actions together to make sure this is not rate limit problem later on.

**Comment by razbensimon** [comment]
Still happens to us on version 2.1.0. Any suggestions?
this is our usage:
```
- name: setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.16.0
```
