### ISSUE TITLE
Potential caching improvement

### ISSUE THREAD

**Issue by maciekbb** [pnpm/action-setup#23]
In the provided caching example

```
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
```

`pnpm-lock.yaml` hash is a part of the cache key. Does it need to be? It seems that packages stored in the cache are versioned. In the integration guide for Travis it looks like the cache directory is just shared across all the builds https://pnpm.io/pl/continuous-integration#travis
