### ISSUE TITLE
Add option to use latest pnpm

### ISSUE THREAD

**Issue by ai** [pnpm/action-setup#25]
I want an option or `version` value to use latest `pnpm` version.

```yml
    - uses: pnpm/action-setup@v2
      with:
        version: latest
```

## Motivation

I have many open source projects and it is hard to update `pnpm` in all of them.

## Side Effect

I understand that some projects need repeatability for CI. So `latest` will not fit their use case. But my projects are small and for my case repeatability is not so important compare to maintainability.

We can promote exact version in docs and keep `latest` only for people who need it.
