### ISSUE TITLE
Add setup-node code to examples

### ISSUE THREAD

**Issue by rajasegar** [pnpm/action-setup#37]
We are calling it out that this action does not setup node and we have to explicitly do it, but sometimes it is not obviously enough to read through the examples till the end and find out about the warning. Instead we can add setup-node code in the README examples itself so that it becomes absolutely apparent. 
Something like below:
```
on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
 ```
If this is okay, will raise a PR for the same.
