### ISSUE TITLE
Publisher verification

### ISSUE THREAD

**Issue by TheAlot** [pnpm/action-setup#43]
Some companies have pretty strict repository security settings, and it is currently not possible to use pnpm (in github actions) in an organization where `Allow Marketplace actions by verified creators` is enabled.

I noticed that the pnpm organization has verified it's domain, so according [the docs](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization), pnpm should be able to apply for publisher verification.

Is this possible? or is there something preventing it from happening?

**Comment by zkochan** [comment]
For some reason, I can't.

![image](https://user-images.githubusercontent.com/1927579/171998078-220c06c7-3c22-4153-8c7b-085fc2396e57.png)

**Comment by TheAlot** [comment]
It seems I ([like many others](https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009)) misread the docs I linked in the issue description. According to [this thread](https://github.community/t/any-risks-of-moving-already-published-action-repository/163739/8) an organization can only receive `verified creator` status on their actions if they are a partner of github ([read more here](https://partner.github.com/)).

This process seems to be much more complicated, and I understand if it is beyond the scope of pnpm as an organization. Sorry for not realizing this when I opened the issue, you can close this whenever 😄

**Comment by moander** [comment]
My solution is curl bash. It's lightning fast. pnpm+nodejs installed in 2+3 seconds!
```yaml
      - name: Install pnpm
        run: curl -fsSL https://gist.githubusercontent.com/moander/94dca738d0b5b8acacbf898348f7d98a/raw/e209ffa62697a06a40470aaabd20304eb00753fb/pnpm-install.sh | bash -

      - name: Detect .node-version
        run: curl -fsSL https://gist.githubusercontent.com/moander/94dca738d0b5b8acacbf898348f7d98a/raw/e209ffa62697a06a40470aaabd20304eb00753fb/node-version.sh | bash -

      - run: pnpm -g env use ${{ env.NODE_VERSION }}
```
<img width="546" alt="image" src="https://user-images.githubusercontent.com/380191/209929782-d0faae91-a68b-4d19-a4f3-ee0bd3b30177.png">
