### ISSUE TITLE
Does your README.md's cache setup equivalent to actions/setup-node@v3 cache setup

### ISSUE THREAD

**Issue by TriStarGod** [pnpm/action-setup#51]
I see two cache setups (one [here](https://github.com/pnpm/action-setup#readme) and the other on [setup-node](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data))  and I'm unsure which one is the latest or if either made a difference.

**Comment by riderx** [comment]
same, none seems to works

**Comment by janosh** [comment]
I also noticed that `cache: pnpm` doesn't work.

```yml
- name: Set up node
  uses: actions/setup-node@v3
  with:
    cache: pnpm
```

Looks like this was reported: https://github.com/actions/setup-node/issues/479

**Comment by melMass** [comment]
The sample from the readme works, there is just a small issue on windows, see #61 or #62 :

```yaml
- name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

- uses: actions/cache@v3
  name: Setup pnpm cache
  with:
    path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    restore-keys: |
      ${{ runner.os }}-pnpm-store-

```

**Comment by riderx** [comment]
what nodejs version ?
i'm speaking about 16.
i sis try both way but now i'm sticking to this one:
https://github.com/actions/setup-node

**Comment by melMass** [comment]
@riderx Using 16 too, you can check my full sample that just worked here:

https://github.com/mtb-tools/vscode-mono-workspace/actions/runs/3272609632/workflow

**Comment by mcmxcdev** [comment]
I was wondering the same thing, we have a setup like:

```
- uses: actions/setup-node@v3
  with:
    node-version-file: "package.json"
    cache: "pnpm"
```

And I am unsure if caching the installation works properly or not between runs.
