### ISSUE TITLE
Example not working on all architecture?

### ISSUE THREAD

**Issue by melMass** [pnpm/action-setup#61]
Hi, 

The sample in the readme works for most platforms but not windows:
https://github.com/mtb-tools/vscode-mono-workspace/actions/runs/3269716040

<img width="221" alt="image" src="https://user-images.githubusercontent.com/7041726/196391412-a5a634cc-a0de-43e2-ab1b-65466382283b.png">

This part is the culprit:

```yaml
- name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT 
```
