### ISSUE TITLE
Add v2 tag

### ISSUE THREAD

**Issue by aminya** [pnpm/action-setup#7]
All the GitHub action packages have something like `v2` to allow using 
```yaml
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
```

Please add a v2 tag.

**Comment by KSXGitHub** [comment]
Tags are supposed to be immutable. A `v1` tag would have to either be outdated or mutable.

If you want to always use latest v1, would don't you just use services like renovate or dependabot to constantly keep track for you?

**Comment by aminya** [comment]
Because I shouldn't care about keeping setup-pnpm up to date. I just want to use v1 and be sure that it works all the time.

All the actions by GitHub already provide this tag. pnpm should not be different.
https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

**Comment by einSelbst** [comment]
hey @aminya, I'm also not sure if I understand you correctly (always use LATEST version of this action or always use SAME version).
If you always want to use the LATEST version you can also

```
- name: Setup PNPM
  uses: pnpm/action@master
  with: 
    version: next
```
