### ISSUE TITLE
pnpm logs two different content-addressable store paths

### ISSUE THREAD

**Issue by axelboc** [pnpm/action-setup#71]
When `pnpm/action-setup` installs pnpm, the logs show:

```
Content-addressable store is at: /home/runner/.pnpm-store/v3
```

![image](https://user-images.githubusercontent.com/2936402/207019321-2676a682-bdf6-4884-a52b-918a1191a71f.png)

But when pnpm installs the dependencies, it logs another path:

```
Content-addressable store is at: /home/runner/setup-pnpm/node_modules/.bin/store/v3
```

![image](https://user-images.githubusercontent.com/2936402/207019682-ce9aa562-518c-4b3e-9dd4-9755d70d7a4d.png)

The second one is correct. Is it because `PNPM_HOME` is set after the installation of pnpm instead of before?

I'm not passing anything special to the actions:

```yaml
- name: Install pnpm ⚙️
  uses: pnpm/action-setup@v2
  with:
    version: 7.x

- name: Install dependencies ⚙️
  run: pnpm install --frozen-lockfile
```
