### ISSUE TITLE
Support pnpm 8

### ISSUE THREAD

**Issue by claughinghouse** [pnpm/action-setup#77]
With the release of pnpm 8 it would be awesome to have support for it in actions.

**Comment by thantos** [comment]
I was able to use 8 with lockfile v6 in actions.

```yaml
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8
```

on GHA

```yaml
Run pnpm/action-setup@v2.2.4
  with:
    version: 8
    dest: ~/setup-pnpm
    run_install: null
```

**Comment by tksst** [comment]
I specified a pnpm version in `package.json`
```
  "packageManager": "pnpm@8.0.0",
```

and it works fine with pnpm/action-setup.


Note that pnpm@8.0.0 + Node.js 14 does not work fine but this is another issue:
#18 
#31

**Comment by fz6m** [comment]
my workaround with using node 14.x and pnpm 8 :

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        if: ${{ matrix.node-version != '14.x' }}
        uses: pnpm/action-setup@v2.2.4

      - name: Install pnpm (node 14)
        if: ${{ matrix.node-version == '14.x' }}
        run: npm install -g @pnpm/exe@8.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
```
