### ISSUE TITLE
Enhancement: cache pnpm-store

### ISSUE THREAD

**Issue by hildjj** [pnpm/action-setup#8]
Correct caching of the `~/.pnpm-store` directory would be cool.

See https://github.com/bahmutov/npm-install for one approach to get ideas from

**Comment by KSXGitHub** [comment]
Use [actions/cache](https://github.com/actions/cache) for that.

**Comment by hildjj** [comment]
Maybe add an example to the docs then?  This is what I came up with:

```yaml
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          # pnpm cache files are stored in `~/.pnpm-store` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
          restore-keys: |
            {{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
```

and 

```
      - name: clean pnpm store
        run: store prune 
```

at the end
