### ISSUE TITLE
Feature Request: add builtin cache support

### ISSUE THREAD

**Issue by trim21** [pnpm/action-setup#80]
like https://github.com/actions/setup-node caching npm and yarn package

suggest a feature to cache installed package with install

**Comment by Kolobok12309** [comment]
@trim21 But `setup-node` has `pnpm` cache option

https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

**Comment by FFdhorkin** [comment]
I would suggest reopening this; we are using a self-hosted runner and **are not** using `setup-node` because node is preinstalled. As such... we can't use `setup-node`'s cache option.

Having to add THREE actions to use pnpm with caching is kinda ugly.

If I have time, I might open a PR for this. @trim21 would you mind reopening?

**Comment by kinland** [comment]
I would suggest reopening this; we are using a self-hosted runner and **are not** using `setup-node` because node is preinstalled. As such... we can't use `setup-node`'s cache option.

Having to add [THREE steps](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time) to use pnpm with caching is kinda ugly.

I'm looking into making a PR for this. @trim21 would you mind reopening?

**Comment by JGJP** [comment]
Would also like to see this. I install pnpm as standalone and want to let it manage my node version. I don't need the setup-node action

**Comment by apetta** [comment]
setup-node doesn't really seem to work, I'm always getting `pnpm cache is not found`

**Comment by trim21** [comment]
> setup-node doesn't really seem to work, I'm always getting `pnpm cache is not found`

you need to setup pnpm first

**Comment by stefanmo** [comment]
> you need to setup pnpm first

@trim21 what does that mean? I'm following the docs and get the pnpm cache is not found message.

```yml
    - name: Checkout
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
```

My guess is you are referring to the install pnpm step, which I do, yet I still get the no cache message. Is there anything else that I am missing?

**Comment by trim21** [comment]
> > you need to setup pnpm first
> 
> @trim21 what does that mean? I'm following the docs and get the pnpm cache is not found message.
> 
> ```yaml
>     - name: Checkout
>       uses: actions/checkout@v4
> 
>     - uses: pnpm/action-setup@v4
>       name: Install pnpm
>       with:
>         version: 9
>         run_install: false
> 
>     - name: Install Node.js
>       uses: actions/setup-node@v4
>       with:
>         node-version: 20
>         cache: "pnpm"
> ```
> 
> My guess is you are referring to the install pnpm step, which I do, yet I still get the no cache message. Is there anything else that I am missing?

I'm using this in my ci

```yaml
inputs:
  node-version:
    description: 'node version'
    required: false
    default: '^22.11.0'

name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '${{ inputs.node-version }}'

    - run: |
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - uses: actions/cache@v4
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-1-node${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-1-node${{ inputs.node-version }}-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
```

**Comment by trim21** [comment]
> > you need to setup pnpm first
> 
> @trim21 what does that mean? I'm following the docs and get the pnpm cache is not found message.
> 
> ```yaml
>     - name: Checkout
>       uses: actions/checkout@v4
> 
>     - uses: pnpm/action-setup@v4
>       name: Install pnpm
>       with:
>         version: 9
>         run_install: false
> 
>     - name: Install Node.js
>       uses: actions/setup-node@v4
>       with:
>         node-version: 20
>         cache: "pnpm"
> ```
> 
> My guess is you are referring to the install pnpm step, which I do, yet I still get the no cache message. Is there anything else that I am missing?

This works for me, you can take a look:

https://github.com/jesec/flood/blob/80825db785efa4bd29eb2ec9218afdcdec39f031/.github/workflows/build.yml

**Comment by mhdcodes** [comment]
Adding this for reference

```yml
name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
```
