### ISSUE TITLE
Using pnpm/action-setup in a subdirectory of a git repoository is giving: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by andresgutgon** [pnpm/action-setup#81]
# WHAT?
Hi, I'm trying to use this GitHub Action in a project that looks like this:
```
myproject
  |-- .github/workflows/client-ci.yml
  |-- backend
  |-- client
```

I want to use `pnpm` inside `myproject/client/package.json` folder but this action:

``` yaml
 - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
```
It's giving this error:
```
Running self-installer...
  [Error: ENOENT: no such file or directory, open '/home/runner/work/myproject/myproject/package.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/runner/work/myproject/myproject/package.json'
  }
```

## Specify destination
I also tried setting destination. But I get the same error.
```yaml
 - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          dest: ~+/client
```

I would appreciate any help. Thanks!

**Comment by andresgutgon** [comment]
Ok I made some "progress" but not sure is the way to go:

To solve the `package.json` ENOENT not found file error I duplicated the `package.json` inside `myproject/client/package.json` outside in `myproject/package.json` 

And that allowed the CI move to fail in the `Build, lint and type-check` step which is my [Turbo repo](https://turbo.build/) project with `pnpm`

With this error:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/49499/235301972-203adfd7-f808-4577-ae8e-3760cb7f03ac.png">


This is my full `.github/workflows/client-ci.yml` file

``` yaml
name: CI client

on:
  push:
    paths:
      - client/**
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.ref }}-client
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  changes:
    name: Check changes files
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
  lint_and_types:
    name: Lint and Type check
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' && (github.event_name == 'push' || !github.event.pull_request.draft) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Build, lint and type-check
        run: pnpm turbo build lint types
        env:
          SKIP_ENV_VALIDATION: true

      - name: Check workspaces
        run: pnpm manypkg check

```

**Comment by andresgutgon** [comment]
Ok I found what was my issue. 

This line is looking always in the root of the repo: https://github.com/pnpm/action-setup/blob/11dd14d0c0916e1ad9ff1938d8d4ea509bebfe10/src/install-pnpm/run.ts#L47

The solution was to use `version` param:

``` yaml
- name: Setup pnpm
  uses: pnpm/action-setup@v2.2.4
  with:
    version: 7.15.0
```

So this way this action doesn't try to find a `package.json` in root of the repo.

I hope this can help someone : )

**Comment by robotkutya** [comment]
Is there a fix without pinning the version to 7.x.x?

**Comment by robotkutya** [comment]
Doesn't this mean that it pins the version...?!
https://github.com/pnpm/action-setup#version

Sorry if I'm being dumb.

**Comment by andresgutgon** [comment]
I guess if you put a version there that's the version used by the github action. So yes, that would be pinned. 

But I think anyway is a good practice to pin your project to an specific `pnpm` version. Either by setting `packageManager` in your root `package.json` or by setting it in the github action.

**Comment by robotkutya** [comment]
Okay, gotcha, thanks!

I'm working with a similar setup, do you just add `working-directory: foo` whenever you run a command or is there a way to take care of that generally?

**Comment by robotkutya** [comment]
For future reference, you can pin _any_ version and it will work.

Originally I thought you specifically had to pin verison `7.15.0`, but any version will do.

@andresgutgon thanks for the tips!

**Comment by nicodes** [comment]
@andresgutgon @robotkutya I'm facing a similar issue, I've read through the docs and I saw `run_install.cwd` should configure this but I haven't gotten it to work. Does anyone have a working example that we could add to the docs?

**Comment by nicodes** [comment]
Here's a code snippet of what I would expect work based on the docs (my working directory is `web`)

```
- uses: pnpm/action-setup@v2
        with:
          run_install: |
            cwd: web
```

**Comment by nicodes** [comment]
I found a solution by adding `version: 7`

```
- uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - cwd: client
  ```

However I do think this should be changed in a future version to use the more common syntax `working-directory` from the `defaults` like @andresgutgon showed above
