### ISSUE TITLE
Parse package.json from subfolder

### ISSUE THREAD

**Issue by some-user123** [pnpm/action-setup#83]
My `package.json` is not located at top level but in a subfolder at `ui/package.json`.
This is not picked up by this action.
```
Error: Error: ENOENT: no such file or directory, open '/home/runner/work/$repo/$repo/package.json'
```

`actions/setup-node` allows to explicitly define the path, e.g.
```
with:
  node-version-file: 'ui/package.json'
  cache: pnpm
  cache-dependency-path: ui/pnpm-lock.yaml
```

It would be nice to have something similar for this action, e.g.
```
with:
  pnpm-version-file: 'ui/package.json'
```

Setting the working-directory does not work.
```
defaults:
  run:
    working-directory: ./ui
```
