### ISSUE TITLE
How to cache pnpm ?

### ISSUE THREAD

**Issue by seepine** [pnpm/action-setup#87]
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.30.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Dependent installation
        run: pnpm i

```
It download pnpm every time.

![image](https://github.com/pnpm/action-setup/assets/93666053/8c50c740-8606-49ba-b1ed-4bb0106ddefa)
