### ISSUE TITLE
Installing pnpm when the package.json isn't in the root directory

### ISSUE THREAD

**Issue by lukey-aleios** [pnpm/action-setup#91]
Hi,

I'm working on a project with a separate backend & frontend directories, with individual package.json files. This step causes an issue for me because it fails when there isn't a package.json file in the top directory. Here's the line that is the likely culprit:

https://github.com/pnpm/action-setup/blob/0b715c7ebbf3cf2174d1386336c5f6d3d8d5504a/src/install-pnpm/run.ts#L14

Do you know any workaround for this?

**Comment by KSXGitHub** [comment]
You can specify `package_json_file` as an input: https://github.com/pnpm/action-setup/tree/v2.4.0#package_json_file

**Comment by lukey-aleios** [comment]
Ah, this was resolved! Nice work

**Comment by konojunya** [comment]
この issue をみた人がより理解できるようにするために root dir に package.json を持たない場合の pnpm-setup を使う方法として重要な点を列挙しておきます。

- github actions の working-directory を指定していること
- run_install の option として cwd を指定していること

上記2つを満たせば、 root に package.json を持たないプロジェクトでも `pnpm/action-setup` を使うことができるでしょう。

```yaml
name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: foo

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
              cwd: foo
```

ref: https://github.com/konojunya/not-root-pnpm-setup/actions/runs/7768165983/job/21185784600
